#2290-Improve questionset
cerpus/Edlib pull request #2292
Opened 2023-05-04 09:31 UTC by ssethupathy

2023-05-05 13:58 UTC, emmachughes requested changes

2023-05-05 13:58 UTC, emmachughes commented on sourcecode/apis/contentauthor/resources/assets/react/components/QuestionContentType/components/QuestionCard/QuestionCardLayout.js
> +                        aria-label="Delete button"
`aria-label` should describe what the button does, not what the button is. This must also be translatable.

2023-05-05 13:58 UTC, emmachughes commented on sourcecode/apis/contentauthor/resources/assets/react/components/QuestionContentType/components/QuestionCard/components/Image/ImageLayout.js
> +                    aria-label="Add image"
The button is the `<input type="file">` created by the DropZone component. The `aria-label` must be placed on that.

<img width="532" alt="image" src="https://user-images.githubusercontent.com/84008144/236475135-858b7787-f227-459b-91bb-a9cc95ce7140.png">

When using keyboard navigation, the button also has no indication it is focused.

2023-05-05 13:58 UTC, emmachughes commented on sourcecode/apis/contentauthor/resources/assets/react/components/QuestionContentType/components/QuestionCard/components/Answer/AnswerLayout.js
> +                 aria-label="Delete button"
Not translatable, doesn't describe what the button does.

2023-05-05 13:58 UTC, emmachughes commented on sourcecode/apis/contentauthor/resources/assets/react/components/QuestionContentType/components/QuestionCard/components/AddAnswer/index.js
> +                aria-label="Add answers"
Must be translatable, and only one answer is added.

2023-05-10 08:54 UTC, chrieinv requested changes

2023-05-10 08:54 UTC, chrieinv commented on sourcecode/apis/contentauthor/resources/assets/react/components/QuestionContentType/components/QuestionCard/QuestionCard.scss
> +  padding-right: 0px;
Don't specify length unit for 0 values

2023-05-10 08:54 UTC, chrieinv commented on sourcecode/apis/contentauthor/resources/assets/react/components/QuestionContentType/components/QuestionCard/QuestionCardLayout.js
> +    const intl = useIntl()
Prefer to deconstruct: `const { formatMessage }  = useIntl();`

2023-05-10 08:54 UTC, chrieinv commented on sourcecode/apis/contentauthor/resources/assets/react/components/QuestionContentType/components/QuestionCard/components/AddAnswer/index.js
> +    const intl = useIntl();
Deconstruct

2023-05-10 08:54 UTC, chrieinv commented on sourcecode/apis/contentauthor/resources/assets/react/components/QuestionContentType/components/QuestionCard/components/AddAnswer/index.js
> +        <div className="addAnswerContainer" onClick={onClick} style={styles.dividerContainer}>
Move the CSS styles to the CSS class used, button styles can also be moved. The `styles.divider` seems unused.

2023-05-10 08:54 UTC, chrieinv commented on sourcecode/apis/contentauthor/resources/assets/react/components/QuestionContentType/components/QuestionCard/components/AddCard/index.js
> +    const intl = useIntl();
Deconstruct

2023-05-10 08:54 UTC, chrieinv commented on sourcecode/apis/contentauthor/resources/assets/react/components/QuestionContentType/components/QuestionCard/components/AddCard/index.js
> +    const useStyles = makeStyles((theme) => ({
Avoid using several different ways of styling. Use either the current or the new, not both. So either move `addNewQuestionContainer` to `useStyles` or move `largeButton` to `styles`.

2023-05-10 08:54 UTC, chrieinv commented on sourcecode/apis/contentauthor/resources/assets/react/components/QuestionContentType/components/QuestionCard/components/Answer/AnswerLayout.js
> +    const intl = useIntl();
Deconstruct

2023-05-10 08:54 UTC, chrieinv commented on sourcecode/apis/contentauthor/resources/assets/react/components/QuestionContentType/components/QuestionCard/components/Image/ImageLayout.js
> +    const intl = useIntl();
Deconstruct

2023-05-10 08:54 UTC, chrieinv commented on sourcecode/apis/contentauthor/resources/assets/react/components/QuestionContentType/components/QuestionCard/components/Image/ImageLayout.js
> +import { useState } from 'react';
Join with line 1

2023-05-10 08:54 UTC, chrieinv commented on sourcecode/apis/contentauthor/resources/assets/react/components/RichEditor/RichEditor.scss
> +
There should be only one empty line at the end of files

2023-05-12 14:01 UTC, chrieinv requested changes

2023-05-22 13:45 UTC, chrieinv approved these changes

2023-05-22 13:52 UTC, emmachughes approved these changes

2023-05-22 13:52 UTC, merged