2516-search filter options
cerpus/Edlib pull request #2566
Opened 2023-10-05 12:49 UTC by ssethupathy

2023-10-06 07:41 UTC, chrieinv requested changes

2023-10-06 07:41 UTC, chrieinv commented on sourcecode/hub/resources/views/components/filter-desktop.blade.php
> +    <select class="form-select" id="languageDropdown">
Select element does not have an associated label or ARIA label

2023-10-06 07:41 UTC, chrieinv commented on sourcecode/hub/resources/views/components/filter-desktop.blade.php
> +    <select class="form-select" id="lastChangedDropdown">
Select element does not have an associated label or ARIA label

2023-10-06 07:41 UTC, chrieinv commented on sourcecode/hub/resources/views/components/search-query.blade.php
Name of the file is a bit confusing. It has nothing to do with search, and it's not a query. This is displaying the selected filter options.

2023-10-06 07:41 UTC, chrieinv commented on sourcecode/hub/resources/views/components/search-query.blade.php
> +                <i class="bi bi-x"></i>
This should be a close button

2023-10-06 07:41 UTC, chrieinv commented on sourcecode/hub/resources/views/components/search-query.blade.php
> +                <i class="bi bi-x"></i>
This should be a close button

2023-10-06 07:41 UTC, chrieinv commented on sourcecode/hub/resources/views/components/search-query.blade.php
> +            <span class="col-auto badge text-bg-primary">
This should be a separate component

2023-10-06 07:41 UTC, chrieinv commented on sourcecode/hub/resources/views/components/search-query.blade.php
> +    <div class="search-query">
Class does not exist

2023-10-06 07:41 UTC, chrieinv commented on sourcecode/hub/resources/css/layout.scss
> +    border: 1px solid var(--components-input-focused-border, #ccc);
Color of the border should be set in theme

2023-10-16 06:52 UTC, chrieinv requested changes

2023-10-16 06:52 UTC, chrieinv commented on sourcecode/hub/database/migrations/2023_10_11_080000_fix_missing_social_id_uniqueness.php
Why are you changing this file?

2023-10-16 06:52 UTC, chrieinv commented on sourcecode/hub/resources/css/theme.scss
`theme.scss` is for color only, rest goes in the `layout.scss`

2023-10-16 06:52 UTC, chrieinv commented on sourcecode/hub/resources/views/components/content/search.blade.php
> +                        placeholder="Type to Search..."
Should be translateable

2023-10-16 06:52 UTC, chrieinv commented on sourcecode/hub/resources/views/components/content/search.blade.php
> +                            <i class="bi bi-search"></i>
use the `x-icon` component

2023-10-16 06:52 UTC, chrieinv commented on sourcecode/hub/resources/views/components/content/search.blade.php
> +<x-selected-filter-options/>
This component does not exist

2023-10-16 06:52 UTC, chrieinv commented on sourcecode/hub/resources/views/components/badge-component.blade.php
> +<span class="col-auto badge text-bg-primary">
Unused component

2023-10-16 06:54 UTC, chrieinv requested changes

2023-10-16 06:54 UTC, chrieinv commented on sourcecode/hub/resources/views/components/badge-component.blade.php
Unused component

2023-10-16 07:02 UTC, emmachughes commented on sourcecode/hub/database/migrations/2023_10_11_080000_fix_missing_social_id_uniqueness.php
The php-cs-fixer bot added this change. There's an issue where it can't apply fixes on commits pushed directly to the hubbub branch, so the fixing happens on the next PR instead.

2023-10-16 07:04 UTC, chrieinv commented on sourcecode/hub/database/migrations/2023_10_11_080000_fix_missing_social_id_uniqueness.php
OK, good to know

2023-10-17 08:29 UTC, chrieinv requested changes

2023-10-30 09:40 UTC, chrieinv approved these changes

2023-10-30 09:59 UTC, merged